Create DATABASE ShopQuanAo
USE ShopQuanAo

GO


CREATE TABLE ACOUNT 
(
	ID INT NOT NULL PRIMARY KEY Identity(1,1),
	EMAIL VARCHAR(50) NOT NULL,
	MAT_KHAU VARCHAR(100),
	LINK_ANH CHAR(50),
	HO_TEN NVARCHAR(35) NOT NULL,
	PHONE CHAR(12) NOT NULL,
	NGAY_DANG_KY DATETIME  DEFAULT GETDATE(),
	DIA_CHI NVARCHAR (40) NOT NULL,
	TRANG_THAI BIT DEFAULT 0
)


GO

CREATE TABLE LOAI_SAN_PHAM
 (
	ID_LOAI_SP INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TEN_LOAI_SP NVARCHAR(30) NOT NULL,
	SLUG VARCHAR(40) NOT NULL,
	TRANG_THAI BIT DEFAULT 1,
	ID_CHA INT DEFAULT 0,
	NGAY_TAO DATETIME DEFAULT GETDATE()
 )

 GO
 CREATE TABLE SAN_PHAM(
	MA_SP CHAR(20) NOT NULL PRIMARY KEY,
	ID_LSP INT NOT NULL,
	TEN_SP NVARCHAR(50) NOT NULL,
	SLUG NVARCHAR(70) NOT NULL,
	MO_TA NVARCHAR(255) ,
	MO_TA_CHI_TIET NTEXT,
	LINK_ANH_CHINH VARCHAR(50),
	LIST_ANH_KEM VARCHAR(250),
	SO_LUONG_TONG INT DEFAULT 0,
	GIA_NHAP DECIMAL(15,4) NOT NULL ,
	GIA_BAN DECIMAL(15,4) NOT NULL ,
	GIAM_GIA INT DEFAULT 0,
	DON_VI_TINH NVARCHAR(30),
	LUOT_XEM INT DEFAULT 0,
	TRANG_THAI BIT DEFAULT 0,
	NOI_BAT BIT DEFAULT 0,
	NGAY_TAO DATETIME DEFAULT GETDATE()
)
GO
 
 CREATE TABLE COLOR
 (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TEN_MAU NVARCHAR(15) NOT NULL,
	SLUG VARCHAR(20),
	MA_MAU VARCHAR(30) ,
	MA_SP CHAR(20),
	IMAGES VARCHAR(100), 
	TRANG_THAI  BIT DEFAULT 1, 
 )

 GO 
 CREATE TABLE SIZE(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TEN_SIZE VARCHAR(15) ,
	SLUG VARCHAR (20),
	MO_TA NVARCHAR(50),
	TRANG_THAI BIT DEFAULT 1
 )
 GO

 CREATE TABLE SAN_PHAM_CHI_TIET(
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_SIZE INT NOT NULL,
	ID_COLOR INT NOT NULL ,
	MA_SP CHAR(20) NOT NULL ,
	SLUG NVARCHAR(80) NOT NULL,
	SO_LUONG INT ,
	TRANG_THAI BIT DEFAULT 0, 
	NGAY_TAO DATETIME DEFAULT GETDATE(),
 ) 

 CREATE TABLE COMMENT(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	MA_SP CHAR(20) NOT NULL,
	ID_KH INT NOT NULL,
	NOIDUNG NVARCHAR(300) ,
	NGAY_TAO DATETIME DEFAULT GETDATE()
 )

 GO
 CREATE TABLE BAI_VIET
 (
	MA_BV INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIEU_DE NVARCHAR(100) NOT NULL,
	MO_TA NVARCHAR(255) ,
	SLUG VARCHAR (120) NOT NULL UNIQUE,
	IMAGES VARCHAR(100),
	NOI_DUNG NTEXT,
	NOI_BAT BIT DEFAULT 0,
	TRANG_THAI BIT DEFAULT 0,
	NGAY_DANG DATETIME DEFAULT GETDATE()
 )

 Alter table Bai_Viet add NOI_DUNG NTEXT

 GO
  CREATE TABLE SLIDE
 (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIEU_DE NVARCHAR(50),
	LINK VARCHAR(100) NOT NULL,
	IMAGES VARCHAR(100),
	STT TINYINT DEFAULT 0,
	TRANG_THAI BIT DEFAULT 0,
	NOI_BAT BIT DEFAULT 0,
	NGAY_DANG DATETIME DEFAULT GETDATE()
 )
 GO

   CREATE TABLE BANNER
 (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TIEU_DE NVARCHAR(50),
	LINK VARCHAR(100) NOT NULL,
	IMAGES VARCHAR(100),
	NOI_DUNG VARCHAR(255),
	TRANG_THAI BIT DEFAULT 0,
	NOI_BAT BIT DEFAULT 0,
	NGAY_DANG DATETIME DEFAULT GETDATE()
 )
 GO

 CREATE TABLE KHACH_HANG
 (
	ID INT NOT NULL IDENTITY(1,1) primary key,
	TEN_KH NVARCHAR(50) NOT NULL,
	SDT NVARCHAR(15) NOT NULL ,
	IMAGES VARCHAR(200)  ,
	EMAIL VARCHAR(50) NOT NULL,
	MK VARCHAR(100) NOT NULL,
	DIA_CHI NVARCHAR(50) NOT NULL,
	TRANG_THAI BIT DEFAULT 0,
	NGAY_TAO DATETIME DEFAULT GETDATE()
 )
 go


 CREATE TABLE STATUS_HOA_DON
 (
	ID INT PRIMARY KEY IDENTITY(1,1),
	STATUS_ORDER NVARCHAR(20) NOT NULL
 )
 GO
 INSERT INTO STATUS_HOA_DON(STATUS_ORDER) VALUES
 (N'Đặt Hàng'),
 (N'Giao Hàng'),
 (N'Hoàn Thành'),
 (N'Hủy Đơn Hàng');
 GO

 CREATE TABLE HOA_DON 
 (
	MA_HD INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_KH INT NOT NULL,
	TEN_NHAN_HANG NVARCHAR(30) ,
	NGAY_MUA DATETIME DEFAULT GETDATE(),
	DIA_CHI_NHAN NVARCHAR(50) ,
	SDT_NHAN CHAR(15) ,
	TONG_TIEN DECIMAL(15,4)DEFAULT 0 ,
	TRANG_THAI INT DEFAULT 1,
	GHI_CHU NVARCHAR(50) 
)
 go




 CREATE TABLE CHI_TIET_HOA_DON 
 (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1) ,
	ID_HD INT not null,
	ID_SP_CT INT not null ,
	SP_SIZE_MAU NVARCHAR(80) ,
	DON_VI_TINH NVARCHAR(30) ,
	SL_MUA INT default 0,
	GIA_BAN DECIMAL(15,4) default 0 
 )
GO


--- TRIGGER tính tổng số lượng sản phẩm theo tổng số lượng san-pham-chi-tiet hiện có 
	/* cập nhật số lượng hàng trong kho sau khi thêm sô lượng vào bảng chi tiết*/
	CREATE TRIGGER TRG_INSERT_SO_LUONG_CHI_TIET_SP ON SAN_PHAM_CHI_TIET AFTER INSERT AS 
	BEGIN
		UPDATE SAN_PHAM SET SO_LUONG_TONG = SO_LUONG_TONG + (SELECT SO_LUONG FROM inserted WHERE inserted.MA_SP = SAN_PHAM.MA_SP) 
		FROM SAN_PHAM  JOIN inserted  ON SAN_PHAM.MA_SP = inserted.MA_SP
	
	END
	GO
	/* cập nhật hàng trong kho sau khi cập nhật đặt hàng */
	CREATE TRIGGER TRG_UPDATE_SO_LUONG_CHI_TIET_SP on SAN_PHAM_CHI_TIET after update AS
	BEGIN
		UPDATE SAN_PHAM SET SO_LUONG_TONG = SO_LUONG_TONG + (SELECT SO_LUONG FROM inserted WHERE inserted.MA_SP = SAN_PHAM.MA_SP) -
		(SELECT SO_LUONG FROM deleted WHERE deleted.MA_SP = SAN_PHAM.MA_SP)
		FROM SAN_PHAM  JOIN deleted  ON SAN_PHAM.MA_SP = deleted.MA_SP
	end
	GO
	/* cập nhật hàng trong kho sau khi hủy đặt hàng */
	CREATE TRIGGER TRG_DELETE_SO_LUONG_CHI_TIET_SP ON SAN_PHAM_CHI_TIET FOR DELETE AS 
	BEGIN
		UPDATE SAN_PHAM SET SO_LUONG_TONG = SO_LUONG_TONG - (SELECT SO_LUONG FROM deleted WHERE deleted.MA_SP = SAN_PHAM.MA_SP) 
		FROM SAN_PHAM  JOIN deleted  ON SAN_PHAM.MA_SP = deleted.MA_SP
	END
--- end


select * from ACOUNT

UPDATE HOA_DON set TRANG_THAI = 1 where MA_HD = 1
select * from CHI_TIET_HOA_DON
update CHI_TIET_HOA_DON set GIA_BAN = 200000 , DON_VI_TINH = N'chiếc' where id = 3